version: '3.8'

services:
  app:
    container_name: my_project_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/scr/app
    ports:
      - ${POSTGRES_PORT}:8000
    restart: always
    env_file:
      - .env

  db:
    container_name: my_project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=61891 
    ports:
      - ${POSTGRESS_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data     
    restart: always
  